# OpenMP run
CFLAGS += -O2 -L$(BASILISK)/gl -lglutils -lfb_osmesa -lGLU -lOSMesa -lm -fopenmp
include $(BASILISK)/Makefile.defs

# MPI run
#CFLAGS += -O2 -L$(BASILISK)/gl -lglutils -lfb_osmesa -lGLU -lOSMesa -lm 
#include $(BASILISK)/Makefile.defs